server:
  port: 9010
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:SunAutumn/week-config.git
          force-pull: true
          passphrase: sun19890317

eureka:
  instance:
    lease-renewal-interval-in-seconds: 20
    prefer-ip-address: true
    ip-address: 192.168.50.157
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9001/eureka/